# Generated by Django 4.1.13 on 2024-04-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tipo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='registro',
            name='valor',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
