# Generated by Django 4.1.13 on 2024-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_remove_sensor_ultimo_registro_remove_sensor_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='valores',
            new_name='registros',
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_dispositivo_th',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
