# Generated by Django 4.1.13 on 2024-04-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_rename_valores_sensor_registros_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='registros',
            new_name='registros_sensor',
        ),
    ]
