# Generated by Django 4.1.13 on 2024-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
