# Generated by Django 4.1.13 on 2024-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0002_alter_hospital_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='numBoxes',
            field=models.IntegerField(blank=True),
        ),
    ]
