# Generated by Django 4.1.13 on 2024-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0003_alter_hospital_numboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
