# Generated by Django 4.1.13 on 2024-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_remove_box_valor'),
        ('pacientes', '0001_initial'),
        ('hospitales', '0004_alter_hospital_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='numBoxes',
        ),
        migrations.AddField(
            model_name='hospital',
            name='boxes',
            field=models.ManyToManyField(to='boxes.box'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pacientes',
            field=models.ManyToManyField(to='pacientes.paciente'),
        ),
    ]
