# Generated by Django 4.1.13 on 2024-03-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
                ('sensores', models.ManyToManyField(to='sensores.sensor')),
                ('tareas', models.ManyToManyField(to='tareas.tarea')),
            ],
        ),
    ]
