# Generated by Django 4.1.13 on 2024-03-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='valor',
        ),
    ]
