apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
      - name: microservicio-container
        image: tu-imagen-de-python:latest
        ports:
        - containerPort: 5000

apiVersion: v1
kind: Service
metadata:
  name: microservicio-service
spec:
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP