# Generated by Django 4.1.13 on 2024-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='valor',
        ),
        migrations.AddField(
            model_name='tarea',
            name='audio_recordatorio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
