# Generated by Django 4.1.13 on 2024-03-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_tarea_valor_tarea_audio_recordatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tipo',
            new_name='prioridad',
        ),
    ]
